### ISSUE TITLE
macos10.12.5 safari 10.1.1 工具首页布局错位

### ISSUE THREAD

**Issue by sdc6882278** [Javran/kancepts#1]
环境：macos10.12.5 safari 10.1.1 语言中文
首页远征规划页的布局错位。
截图如下：
<img width="1139" alt="2017-07-14 8 06 45" src="https://user-images.githubusercontent.com/5699389/28211621-3bd881fc-68d0-11e7-8a6d-cc0e7afe261e.png">
测试 chrome 59.3071 x64 无此现象。

**Comment by Javran** [comment]
hmm, 暂时不确定这个问题该怎么调整,我也没法重现. 刚才更新了一个版本,设置了一下最小宽度,你看看还会不会有这种问题

**Comment by sdc6882278** [comment]
重新查看了，问题依旧。先关闭吧，估计是mac平台的兼容性问题。


在 2017年7月15日，上午11:28，Javran Cheng <notifications@github.com> 写道：

hmm, 暂时不确定这个问题该怎么调整,我也没法重现. 刚才更新了一个版本,设置了一下最小宽度,你看看还会不会有这种问题

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Javran/kancepts/issues/1#issuecomment-315506194>, or mute
the thread

**Comment by Javran** [comment]
应要求先关闭了. 应用是以 react-bootstrap 写的,使用前先试试这个页面:

https://react-bootstrap.github.io/components

的显示是否正常,如果不正常的话我这边也无能为力...
